function k(b,a,c,d){b.i.ra(b.U,a,c,d,void 0)}function p(b,a,c,d){b.i.v?k(b,a,c,d):b.i.zb()._OnMessageFromDOM({type:"event",component:b.U,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function q(b,a,c){b.i.h(b.U,a,c)}function r(b,a){for(const [c,d]of a)q(b,c,d)}window.R=class{constructor(b,a){this.i=b;this.U=a}Ka(){}};window.qb=class{constructor(b){this.Ya=b;this.Lb=5;this.M=-1;this.ja=-Infinity;this.Qb=()=>{this.M=-1;this.ja=Date.now();this.V=!0;this.Ya();this.V=!1};this.Za=this.V=!1}};
"use strict";function aa(b,a){const c=a.elementId,d=b.Ma(a);b.s.set(c,d);d.style.boxSizing="border-box";a.isVisible||(d.style.display="none");d.addEventListener("focus",()=>{t(b,"elem-focused",c)});d.addEventListener("blur",()=>{t(b,"elem-blurred",c)});b.ga&&document.body.appendChild(d)}function u(b,a,c){q(b,a,d=>{const e=b.s.get(d.elementId);return c(e,d)})}function t(b,a,c){var d;d||(d={});d.elementId=c;k(b,a,d)}
window.jb=class extends self.R{constructor(b){super(b,"iframe");this.s=new Map;this.ga=!0;r(this,[["create",a=>aa(this,a)],["destroy",a=>{a=a.elementId;const c=this.s.get(a);this.Na(c);this.ga&&c.parentElement.removeChild(c);this.s.delete(a)}],["set-visible",a=>{this.ga&&(this.s.get(a.elementId).style.display=a.isVisible?"":"none")}],["update-position",a=>{if(this.ga){var c=this.s.get(a.elementId);c.style.left=a.left+"px";c.style.top=a.top+"px";c.style.width=a.width+"px";c.style.height=a.height+"px";
a=a.fontSize;null!==a&&(c.style.fontSize=a+"em")}}],["update-state",a=>{this.s.get(a.elementId);this.Pa()}],["focus",a=>this.wa(a)],["set-css-style",a=>{const c=this.s.get(a.elementId),d=a.prop;a=a.val;d.startsWith("--")?c.style.setProperty(d,a):c.style[d]=a}],["set-attribute",a=>{this.s.get(a.elementId).setAttribute(a.name,a.val)}],["remove-attribute",a=>{this.s.get(a.elementId).removeAttribute(a.name)}]]);u(this,"get-element",a=>a)}Ma(){throw Error("required override");}Na(){}Pa(){throw Error("required override");
}wa(b){var a=this.s.get(b.elementId);b.focus?a.focus():a.blur()}};"use strict";const v=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),w=/android/i.test(navigator.userAgent);let x=0;
function y(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.Vb?new Promise(c=>{const d="c3_resolve_"+x;++x;self[d]=c;a.textContent=b.Zb+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let z=!1,ba=!1;function ca(){if(!z){try{new Worker("blob://",{get type(){ba=!0}})}catch(b){}z=!0}return ba}let A=new Audio;
const da={"audio/webm; codecs=opus":!!A.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!A.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!A.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!A.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!A.canPlayType("audio/mp4"),"audio/mpeg":!!A.canPlayType("audio/mpeg")};A=null;async function ea(b){b=await fa(b);return(new TextDecoder("utf-8")).decode(b)}
function fa(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const B=[];let D=0;window.RealFile=window.File;const E=[],F=new Map,G=new Map;let ha=0;const ia=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");ia.push(b)};const ja=new Set(["cordova","playable-ad","instant-games"]);let ka=!1;
window.C=class b{constructor(a){this.v=a.ac;this.Y=null;this.m="";this.K=a.Yb;this.ca={};this.Ea=this.N=null;this.ha=[];this.j=this.aa=null;this.cb=!1;this.W=null;this.J=-1;this.Pb=()=>this.Gb();this.gb=[];this.g=a.hb;this.Ca="file"===location.protocol.substr(0,4);!this.v||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ca()||(this.v=!1);if("playable-ad"===this.g||"instant-games"===this.g)this.v=!1;if("cordova"===this.g&&this.v)if(w){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);
c&&90<=parseInt(c[1],10)||(this.v=!1)}else this.v=!1;this.ka=this.B=null;"html5"!==this.g||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.h("runtime","cordova-fetch-local-file",c=>this.Cb(c));this.h("runtime","create-job-worker",()=>this.Db());"cordova"===this.g?document.addEventListener("deviceready",()=>this.Sa(a)):this.Sa(a)}nb(){return v&&
"cordova"===this.g}qa(){const a=navigator.userAgent;return v&&ja.has(this.g)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}lb(){return w}Oa(){return w&&ja.has(this.g)}async Sa(a){"macos-wkwebview"===this.g&&this.ya({type:"ready"});if("playable-ad"===this.g){this.B=self.c3_base64files;this.ka={};await this.vb();for(let d=0,e=a.O.length;d<e;++d){var c=a.O[d];this.ka.hasOwnProperty(c)?a.O[d]={Vb:!0,Zb:this.ka[c]}:this.B.hasOwnProperty(c)&&(a.O[d]=URL.createObjectURL(this.B[c]))}}a.Xb?this.m=
a.Xb:(c=location.origin,this.m=("null"===c?"file:///":c)+location.pathname,c=this.m.lastIndexOf("/"),-1!==c&&(this.m=this.m.substr(0,c+1)));a.cc&&(this.ca=a.cc);c=new MessageChannel;this.Y=c.port1;this.Y.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Fb(d));this.W=new self.ob(this);await la(this.W);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,
e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.v?await this.Bb(a,c.port2):await this.Ab(a,c.port2)}ta(a){a=this.ca.hasOwnProperty(a)?this.ca[a]:a.endsWith("/workermain.js")&&this.ca.hasOwnProperty("workermain.js")?this.ca["workermain.js"]:"playable-ad"===this.g&&this.B.hasOwnProperty(a)?this.B[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async pa(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===
this.g&&this.Ca)return a=await this.oa(d.Ub?a:this.K+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}A(){return Math.max(window.innerWidth,1)}u(){return Math.max(window.innerHeight,1)}Ra(a){var c=this.m,d=location.href,e=this.A(),f=this.u(),g=window.devicePixelRatio,
h=b.S(),l=a.jc,m=window.cr_previewImageBlobs||this.B,n=window.cr_previewProjectFileBlobs,ya=window.cr_previewProjectFiles,za=window.hc||"";a=a.hb;var Aa=(new URLSearchParams(self.location.search)).has("debug"),K=this.W;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:l,previewImageBlobs:m,previewProjectFileBlobs:n,previewProjectFileSWUrls:ya,swClientId:za,exportType:a,isDebug:Aa,ife:!!self.ic,jobScheduler:{inputPort:K.Ba,outputPort:K.Ga,
maxNumWorkers:K.Nb},supportedAudioFormats:da,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.K+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.K+"opus.wasm.wasm",isFileProtocol:this.Ca,isiOSCordova:this.nb(),isiOSWebView:this.qa(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Bb(a,c){const d=this.ta(a.bc);"preview"===this.g?(this.N=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((h,l)=>{const m=n=>{this.N.removeEventListener("message",
m);n.data&&"ok"===n.data.type?h():l()};this.N.addEventListener("message",m);this.N.postMessage({type:"construct-worker-init","import":(new URL(d,this.m)).toString()})})):this.N=await this.pa(d,this.m,{type:"module",name:"Runtime",Ub:!0});this.j=document.createElement("canvas");this.j.style.display="none";const e=this.j.transferControlToOffscreen();document.body.appendChild(this.j);window.c3canvas=this.j;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.Ja||[],g=a.O;f=await Promise.all(f.map(h=>
this.H(h)));g=await Promise.all(g.map(h=>this.H(h)));if("cordova"===this.g)for(let h=0,l=a.na.length;h<l;++h){const m=a.na[h],n=m[0];if(n===a.Ia||"scriptsInEvents.js"===n||n.endsWith("/scriptsInEvents.js"))m[1]=await this.H(n)}this.N.postMessage(Object.assign(this.Ra(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:a.na,mainProjectScript:a.Ia,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...ma(this.W)]);this.ha=E.map(h=>
new h(this));this.Qa();na(this.aa);self.c3_callFunction=(h,l)=>{var m=this.aa;return m.i.pb(m.U,{name:h,params:l})};"preview"===this.g&&(self.goToLastErrorScript=()=>this.ra("runtime","go-to-last-error-script"))}async Ab(a,c){this.j=document.createElement("canvas");this.j.style.display="none";document.body.appendChild(this.j);window.c3canvas=this.j;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.ha=E.map(g=>new g(this));this.Qa();var d=a.O.map(g=>"string"===typeof g?(new URL(g,
this.m)).toString():g);Array.isArray(a.Ja)&&d.unshift(...a.Ja);d=await Promise.all(d.map(g=>this.H(g)));await Promise.all(d.map(g=>y(g)));d=self.C3_ProjectScriptsStatus;const e=a.Ia,f=a.na;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.H(h),await y(h),"preview"!==this.g||d[g]||this.Ua(g,"main script did not run to completion")}catch(l){this.Ua(g,l)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.H(h),await y(h);"preview"===this.g&&"object"!==typeof self.dc.ec?
(this.ea(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Ra(a),{isInWorker:!1,messagePort:c,canvas:this.j,runOnStartupFunctions:ia}),na(this.aa),this.Ta(),this.Ea=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Ea,a))}Ua(a,c){this.ea();console.error(`[Preview] Failed to load project main script (${a}): `,
c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Ta(){this.ea()}ea(){const a=window.Sb;a&&(a.parentElement.removeChild(a),window.Sb=null)}async Db(){const a=await oa(this.W);return{outputPort:a,transferables:[a]}}zb(){if(this.v)throw Error("not available in worker mode");return this.Ea}ra(a,c,d,e,f){this.Y.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},
f)}pb(a,c){const d=ha++,e=new Promise((f,g)=>{G.set(d,{resolve:f,reject:g})});this.Y.postMessage({type:"event",component:a,handler:"js-invoke-function",dispatchOpts:null,data:c,responseId:d},void 0);return e}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.Eb(a);if("result"===c)this.Hb(a);else if("runtime-ready"===c)this.Ib();else if("alert-error"===c)this.ea(),alert(a.message);else if("creating-runtime"===c)this.Ta();else throw Error(`unknown message '${c}'`);}Eb(a){const c=a.component,
d=a.handler,e=a.data,f=a.responseId;if(a=F.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.da(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.da(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.da(f,!1,""+h)}):this.da(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}da(a,c,d){let e;d&&d.transferables&&
(e=d.transferables);this.Y.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Hb(a){const c=a.responseId,d=a.isOk;a=a.result;const e=G.get(c);d?e.resolve(a):e.reject(a);G.delete(c)}h(a,c,d){let e=F.get(a);e||(e=new Map,F.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static P(a){if(E.includes(a))throw Error("DOM handler already added");E.push(a)}Qa(){for(const a of this.ha)if("runtime"===a.U){this.aa=a;return}throw Error("cannot find runtime DOM handler");
}Fb(a){this.ra("debugger","message",a)}Ib(){for(const a of this.ha)a.Ka()}static S(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||ka)}static fa(a){ka=!!a}Va(){-1===this.J&&this.gb.length&&(this.J=requestAnimationFrame(this.Pb))}tb(){-1!==this.J&&(cancelAnimationFrame(this.J),this.J=-1)}Gb(){this.J=-1;for(const a of this.gb)a();this.Va()}xa(){this.aa.xa()}rb(){this.cb=!0}kb(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===
a.substr(0,5)}mb(a){return!this.kb(a)}async H(a){return"cordova"===this.g&&(a.startsWith("file:")||this.Ca&&this.mb(a))?(a.startsWith(this.m)&&(a=a.substr(this.m.length)),a=await this.oa(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Cb(a){const c=a.filename;switch(a.as){case "text":return await this.ib(c);case "buffer":return await this.oa(c);default:throw Error("unsupported type");}}La(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,
e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async ib(a){a=await this.La(a);return await ea(a)}sa(){if(B.length&&!(8<=D)){D++;var a=B.shift();this.wb(a.filename,a.$b,a.Tb)}}oa(a){return new Promise((c,d)=>{B.push({filename:a,$b:e=>{D--;this.sa();c(e)},Tb:e=>{D--;this.sa();d(e)}});this.sa()})}async wb(a,c,d){try{const e=await this.La(a),f=await fa(e);c(f)}catch(e){d(e)}}ya(a){if("windows-webview2"===this.g)window.chrome.webview.postMessage(JSON.stringify(a));else if("macos-wkwebview"===
this.g)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async vb(){const a=[];for(const [c,d]of Object.entries(this.B))a.push(this.ub(c,d));await Promise.all(a)}async ub(a,c){if("object"===typeof c)this.B[a]=new Blob([c.str],{type:c.type}),this.ka[a]=c.str;else{let d=await this.yb(c);d||(d=this.xb(c));this.B[a]=d}}async yb(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
c),null}}xb(a){a=this.Jb(a);return this.sb(a.data,a.Wb)}Jb(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{Wb:a,data:d}}sb(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,l;for(l=h=0;h<e;++h)g[h]=a.charCodeAt(l++)|a.charCodeAt(l++)<<8|a.charCodeAt(l++)<<16|a.charCodeAt(l++)<<24;for(d&=
3;d--;)f[l]=a.charCodeAt(l),++l;return new Blob([f],{type:c})}};"use strict";const H=self.C;function pa(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const qa=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),I={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},ra={dispatchUserScriptEvent:!0},J={dispatchRuntimeEvent:!0};
function sa(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function ta(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function L(b){b=URL.createObjectURL(b);try{return await ta(b)}finally{URL.revokeObjectURL(b)}}
function ua(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function va(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await L(b);var d=await ua(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await L(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await L(b)}
function M(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const wa=new Set(["input","textarea","datalist","select"]),xa=new Set(["canvas","body","html"]);function N(b){xa.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ba(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await L(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await va(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let O=!1;document.addEventListener("pause",()=>O=!0);document.addEventListener("resume",()=>O=!1);function na(b){b.ab=!0;b.Da=b.i.A();b.X=b.i.u()}async function Ca(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Da(b){return await self.C3_GetSvgImageSize(b.blob)}
function Ea(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}function Fa(b){self.setTimeout(()=>{b.$a=!0},1E3);"cordova"===b.i.g?(document.addEventListener("pause",()=>P(b,!0)),document.addEventListener("resume",()=>P(b,!1))):document.addEventListener("visibilitychange",()=>P(b,document.hidden));return{isSuspended:!(!document.hidden&&!O)}}
function Ga(b){b.Xa||(b.Xa=!0,window.addEventListener("deviceorientation",a=>{b.l||k(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},I)}),window.addEventListener("deviceorientationabsolute",a=>{b.l||k(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},I)}))}
function Ha(b){b.Wa||(b.Wa=!0,window.addEventListener("devicemotion",a=>{if(!b.l){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});k(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},I)}}))}async function Ia(b){await sa(b.url)}
function Ja(b,a){b.bb=a.message;-1===b.Aa&&(b.Aa=setTimeout(()=>{b.Aa=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.bb)},250))}function Q(b){if(!b.l){var a=H.S();a&&"any"!==b.Ha&&Ka(b);k(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.A(),innerHeight:b.u()})}}function S(b,a){console.warn("[Construct] Fullscreen request failed: ",a);k(b,"fullscreenerror",{isFullscreen:H.S(),innerWidth:b.A(),innerHeight:b.u()})}
function P(b,a){a?b.i.tb():b.i.Va();k(b,"visibilitychange",{hidden:a})}function La(b,a,c){"Backspace"===c.key&&N(c);if(!b.l){var d=qa.get(c.code)||c.code;p(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},I)}}
function T(b,a,c,d){b.l||pa(c)||p(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.o,pageX:c.pageX,pageY:c.pageY+b.o,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}function U(b){window!==window.top&&window.focus();Ma(b.target)&&document.activeElement&&!Ma(document.activeElement)&&document.activeElement.blur()}
function V(b,a,c){if(!b.l){if(b.$&&"pointermove"!==a){var d=b.$;d.V||(-1!==d.M&&(self.clearTimeout(d.M),d.M=-1),d.ja=Date.now())}d=0;"mouse"===c.pointerType&&(d=b.Z);p(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.o,pageX:c.pageX,pageY:c.pageY+b.o,movementX:(c.movementX||0)+b.la,movementY:(c.movementY||0)+b.ma,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||
0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},I);b.la=0;b.ma=0;"mouse"===c.pointerType&&(d="mousemove","pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),T(b,d,c,ra),b.Z=c.buttons)}}
function W(b,a,c){if(!b.l&&!pa(c)){var d=b.Z;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");p(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.o,pageX:c.pageX,pageY:c.pageY+b.o,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},I);b.Z=c.buttons;T(b,c.type,c,ra)}}
function X(b,a,c){if(!b.l)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];p(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.o,pageX:f.pageX,pageY:f.pageY+b.o,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
I)}}function Y(b,a,c){document.body.style.transform="";b.o=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.o=a))}}function Na(b,a,c,d){const e=b.A(),f=b.u();b.L=-1;e!=a||f!=c?k(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:H.S()}):10>d&&Oa(b,e,f,d+1)}
function Oa(b,a,c,d){-1!==b.L&&clearTimeout(b.L);b.L=setTimeout(()=>Na(b,a,c,d),48)}
function Ka(b){b=b.Ha;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",a)}}
function Ma(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
H.P(class extends self.R{constructor(b){super(b,"runtime");this.eb=!0;this.ab=!1;this.L=-1;this.Ha="any";this.Wa=this.Xa=!1;this.F=null;this.l=!1;this.bb="";this.Aa=-1;this.I=this.$=null;this.ma=this.la=0;this.$a=!1;this.Da=b.A();this.X=b.u();this.o=this.ba=0;b.h("canvas","update-size",d=>{var e=this.i;e.cb||(e=e.j,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",
d.displayScale),this.eb&&(e.style.display="",this.eb=!1))});b.h("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.h("runtime","raster-svg-image",d=>Ca(d));b.h("runtime","get-svg-image-size",d=>Da(d));b.h("runtime","set-target-orientation",d=>{this.Ha=d.targetOrientation});b.h("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.h("runtime",
"post-to-debugger",d=>Ea(d));b.h("runtime","go-to-script",d=>Ea(d));b.h("runtime","before-start-ticking",()=>Fa(this));b.h("runtime","debug-highlight",d=>{if(d.show){this.F||(this.F=document.createElement("div"),this.F.id="inspectOutline",document.body.appendChild(this.F));var e=this.F;e.style.display="";e.style.left=d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.F&&(this.F.style.display="none")});b.h("runtime","enable-device-orientation",
()=>Ga(this));b.h("runtime","enable-device-motion",()=>Ha(this));b.h("runtime","add-stylesheet",d=>Ia(d));b.h("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.h("runtime","alert",d=>this.ua(d));b.h("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.h("runtime","set-exporting-to-video",d=>{this.l=!0;const e=document.createElement("h1");
e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.i.j.style.display="";this.i.rb()});b.h("runtime","export-to-video-progress",d=>Ja(this,d));b.h("runtime","exported-to-video",d=>{window.Rb({type:"exported-video",blob:d.blob,time:d.time})});b.h("runtime","exported-to-image-sequence",d=>{window.Rb({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);
window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||M(e)||d.preventDefault()});const c=b.j;window.addEventListener("selectstart",N);window.addEventListener("gesturehold",N);c.addEventListener("selectstart",N);c.addEventListener("gesturehold",N);window.addEventListener("touchstart",N,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",N,{passive:!1}),c.addEventListener("pointerdown",N)):c.addEventListener("touchstart",N);this.Z=
0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Ba,{passive:!1});window.addEventListener("wheel",Ba,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.l&&this.ab){var d=this.A();var e=this.u();if(this.i.Oa()){if(this.$a){if(this.Da===d&&e<this.X){this.ba=this.X-e;Y(this,this.X,this.ba);d=void 0;break a}0<this.ba&&(this.ba=0,Y(this,e,this.ba))}this.Da=d;this.X=e}k(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,
isFullscreen:H.S()});this.i.qa()&&(-1!==this.L&&clearTimeout(this.L),Na(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>Q(this));window.addEventListener("webkitfullscreenchange",()=>Q(this));window.addEventListener("mozfullscreenchange",()=>Q(this));window.addEventListener("fullscreenerror",d=>S(this,d));window.addEventListener("webkitfullscreenerror",d=>S(this,d));window.addEventListener("mozfullscreenerror",d=>S(this,d));if(b.qa())if(window.visualViewport){let d=
Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):M(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=d=>{"entered-fullscreen"===
d?(H.fa(!0),Q(this)):"exited-fullscreen"===d?(H.fa(!1),Q(this)):console.warn("Unknown wrapper message: ",d)};this.Fa=new Set;this.Ob=new WeakSet;this.Mb=!1}Ka(){window.addEventListener("focus",()=>{k(this,"window-focus",null,J)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}k(this,"window-blur",{parentHasFocus:a},J);this.Z=0});window.addEventListener("focusin",a=>{a=a.target;(wa.has(a.tagName.toLowerCase())||M(a))&&k(this,"keyboard-blur",
null,J)});window.addEventListener("keydown",a=>La(this,"keydown",a));window.addEventListener("keyup",a=>La(this,"keyup",a));window.addEventListener("dblclick",a=>T(this,"dblclick",a,I));window.addEventListener("wheel",a=>{this.l||k(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.o,pageX:a.pageX,pageY:a.pageY+this.o,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},I)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",a=>{U(a);
V(this,"pointerdown",a)}),this.i.v&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.$=new self.qb(()=>{V(this,"pointermove",this.I);this.I=null}),this.$.Za=!0,window.addEventListener("pointerrawupdate",a=>{this.I&&(this.la+=this.I.movementX||0,this.ma+=this.I.movementY||0);this.I=a;a=this.$;if(-1===a.M){var c=Date.now(),d=c-a.ja,e=a.Lb;d>=e&&a.Za?(a.ja=c,a.V=!0,a.Ya(),a.V=!1):a.M=self.setTimeout(a.Qb,Math.max(e-d,4))}})):window.addEventListener("pointermove",a=>V(this,"pointermove",
a)),window.addEventListener("pointerup",a=>V(this,"pointerup",a)),window.addEventListener("pointercancel",a=>V(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{U(a);W(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>W(this,"pointermove",a)),window.addEventListener("mouseup",a=>W(this,"pointerup",a)),window.addEventListener("touchstart",a=>{U(a);X(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>X(this,"pointermove",a)),window.addEventListener("touchend",
a=>X(this,"pointerup",a)),window.addEventListener("touchcancel",a=>X(this,"pointercancel",a)));const b=()=>this.xa();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.i.lb()&&!this.i.Oa()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Y(this,this.u(),
navigator.virtualKeyboard.boundingRect.height)}))}A(){return this.i.A()}u(){return this.i.u()}xa(){var b=[...this.Fa];this.Fa.clear();if(!this.Mb)for(const a of b)(b=a.play())&&b.catch(()=>{this.Ob.has(a)||this.Fa.add(a)})}ua(b){alert(b.message)}});"use strict";
async function la(b){if(b.Kb)throw Error("already initialised");b.Kb=!0;var a=b.D.ta(("playable-ad"===b.D.g?b.D.K:"")+"dispatchworker.js");b.za=await b.D.pa(a,b.T,{name:"DispatchWorker"});a=new MessageChannel;b.Ba=a.port1;b.za.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Ga=await oa(b)}function ma(b){return[b.Ba,b.Ga]}
async function oa(b){const a=b.fb.length;var c=b.D.ta(("playable-ad"===b.D.g?b.D.K:"")+"jobworker.js");c=await b.D.pa(c,b.T,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.za.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.fb.push(c);return e.port1}
self.ob=class{constructor(b){this.D=b;this.T=b.m;this.T="preview"===b.g?this.T+"workers/":this.T+b.K;this.Nb=Math.min(navigator.hardwareConcurrency||2,16);this.za=null;this.fb=[];this.Ga=this.Ba=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.C({ac:!0,bc:"workermain.js",O:["scripts/c3runtime.js"],na:[],Ia:"",Yb:"scripts/",Ja:[],hb:"html5"}));"use strict";function Pa(b,a,c){Z(b,a,URL.createObjectURL(new Blob([c.html],{type:"text/html"})));b.ia=!0}
function Z(b,a,c){a.src&&a.src.startsWith("blob:")&&b.ia&&URL.revokeObjectURL(a.src);a.src=c}
self.C.P(class extends self.jb{constructor(b){super(b);this.ia=!1;u(this,"navigate-url",(a,c)=>{Z(this,a,c.url);this.ia=!1});u(this,"display-html",(a,c)=>Pa(this,a,c))}Ma(b){const a=document.createElement("iframe");a.style.position="absolute";a.style.border="none";var c=navigator.userAgent;/iphone|ipad|ipod/i.test(c)&&(c=/(iphone\s+os|ipad[^)]*os)\s+([0-9_]+)/i.exec(c),c=parseInt(c[c.length-1]),12>=c||isNaN(c))&&(a.setAttribute("noresize","noresize"),a.setAttribute("scrolling","no"));b.isVisible||
(a.style.display="none");b.id&&(a.id=b.id);b.allow&&(a.setAttribute("allow",b.allow),b.allow.includes("fullscreen")&&a.setAttribute("allowfullscreen",""));b.enableSandbox&&a.setAttribute("sandbox",b.sandbox);b.url?a.src=b.url:b.html&&Pa(this,a,b);return a}Pa(){}Na(b){Z(this,b,"");this.ia=!1}});"use strict";
async function Qa(b){if(!b.G)try{b.G=await navigator.wakeLock.request("screen"),b.G.addEventListener("release",()=>{console.log("[Construct] Screen wake lock released");b.G=null;k(b,"wake-lock-released")}),console.log("[Construct] Screen wake lock acquired"),k(b,"wake-lock-acquired")}catch(a){console.warn("[Construct] Failed to acquire screen wake lock: ",a),k(b,"wake-lock-error")}}
function Ra(){var b=document.body;const a=b.style;a.setProperty("--temp-sai-top","env(safe-area-inset-top)");a.setProperty("--temp-sai-right","env(safe-area-inset-right)");a.setProperty("--temp-sai-bottom","env(safe-area-inset-bottom)");a.setProperty("--temp-sai-left","env(safe-area-inset-left)");b=getComputedStyle(b);b=[b.getPropertyValue("--temp-sai-top"),b.getPropertyValue("--temp-sai-right"),b.getPropertyValue("--temp-sai-bottom"),b.getPropertyValue("--temp-sai-left")].map(c=>{c=parseInt(c,10);
return isFinite(c)?c:0});a.removeProperty("--temp-sai-top");a.removeProperty("--temp-sai-right");a.removeProperty("--temp-sai-bottom");a.removeProperty("--temp-sai-left");return b}
self.C.P(class extends self.R{constructor(b){super(b,"platform-info");r(this,[["get-initial-state",()=>this.va()],["request-wake-lock",()=>Qa(this)],["release-wake-lock",()=>{this.G&&(this.G.release(),this.G=null)}]]);window.addEventListener("resize",()=>{k(this,"window-resize",{windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:Ra()})});this.G=null}va(){return{screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,
safeAreaInset:Ra(),supportsWakeLock:!!navigator.wakeLock}}});"use strict";function Sa(){}function Ta(b){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>k(b,"sw-message",a.data))}
function Ua(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}
self.C.P(class extends self.R{constructor(b){super(b,"browser");this.g="";r(this,[["get-initial-state",a=>this.va(a)],["ready-for-sw-messages",()=>Ta(this)],["alert",a=>this.ua(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.wa(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>Ua(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?
screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var c=a.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();else if("url"===
c){c=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):"preview"===a||"windows-webview2"===a?window.open(c,"_blank"):this.fc||(2===d?window.top.location=c:1===d?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,a))}],["request-fullscreen",a=>{if("windows-webview2"===this.g||"macos-wkwebview"===this.g)self.C.fa(!0),
this.i.ya({type:"set-fullscreen",fullscreen:!0});else{const c={navigationUI:"auto"};a=a.navUI;1===a?c.navigationUI="hide":2===a&&(c.navigationUI="show");a=document.documentElement;let d;a.requestFullscreen?d=a.requestFullscreen(c):a.mozRequestFullScreen?d=a.mozRequestFullScreen(c):a.msRequestFullscreen?d=a.msRequestFullscreen(c):a.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());d instanceof
Promise&&d.catch(Sa)}}],["exit-fullscreen",()=>{if("windows-webview2"===this.g||"macos-wkwebview"===this.g)self.C.fa(!1),this.i.ya({type:"set-fullscreen",fullscreen:!1});else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch(Sa)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",
a=>{const c=a.prop,d=a.value;var e=a.selector;a=a["is-all"];try{if(e)if(a)var f=Array.from(document.querySelectorAll(e));else{var g=document.querySelector(e);f=g?[g]:[]}else f=[document.documentElement];e=f;for(const h of e)c.startsWith("--")?h.style.setProperty(c,d):h.style[c]=d}catch(h){console.warn("[Browser] Failed to set style: ",h)}}],["get-document-css-style",a=>{{const d=a.prop;a=a.selector;try{const e=document.querySelector(a);var c=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:
{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",e),c={isOk:!1}}}return c}]]);window.addEventListener("online",()=>{k(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{k(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{k(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{k(this,"backbutton")})}va(b){this.g=b.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,
referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}ua(b){alert(b.message)}wa(b){b=b.isFocus;if("nwjs"===this.g){const a="nwjs"===this.g?nw.Window.get():null;b?a.focus():a.blur()}else b?window.focus():window.blur()}});"use strict";
async function Va(b,a){a=a.type;let c=!0;0===a?c=await Wa():1===a&&(c=await Xa());k(b,"permission-result",{type:a,result:c})}async function Wa(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function Xa(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.C.P(class extends self.R{constructor(b){super(b,"touch");q(this,"request-permission",a=>Va(this,a))}});
